CREATE TABLE IF NOT EXISTS fish (
	merchID INTEGER NOT NULL PRIMARY KEY CHECK(merchID > 0),
	species VARCHAR(50) NOT NULL DEFAULT 'N/A',
	genus VARCHAR(50) NOT NULL DEFAULT 'N/A',
	commonName VARCHAR(50) NOT NULL,
	price NUMERIC CHECK(price > 0.00) NOT NULL,
	isInvertebrate BOOLEAN DEFAULT FALSE,
	waterType VARCHAR(50) NOT NULL,
	phRange VARCHAR(50) NOT NULL,
	description VARCHAR(500)
);
CREATE TABLE IF NOT EXISTS plant (
	merchID INTEGER NOT NULL PRIMARY KEY CHECK(merchID > 0),
	species VARCHAR(50) NOT NULL DEFAULT 'N/A',
	genus VARCHAR(50) NOT NULL DEFAULT 'N/A',
	commonName VARCHAR(50) NOT NULL,
	price NUMERIC CHECK(price > 0.00) NOT NULL,
	waterType VARCHAR(50) NOT NULL,
	phRange VARCHAR(50) NOT NULL,
	description VARCHAR(500)
);