INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1001, 'Xiphophorus', 'maculatus', 'Blue Wag Platy', 2.56, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1002, 'Xiphophorus', 'maculatus', 'Mickey Mouse Platy', 1.67, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1003, 'Xiphophorus', 'maculatus', 'Painted Platy', 2.14, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1004, 'Xiphophorus', 'maculatus', 'Sunburst Platy', 2.88, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1005, 'Xiphophorus', 'maculatus', 'Dalmation Platy', 3.12, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');

INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1006, 'Poecilia', 'reticulata', 'Tequila Sunrise Guppy', 3.50, FALSE, 'fresh', '6.8-7.8', 'The Tequila Sunrise Guppy requires an aquarium of at least 10 gallons in size. It is a very peaceful fish and should be housed with tankmates of similar temperament.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1007, 'Poecilia', 'reticulata', 'Fancy Guppy', 4.65, FALSE, 'fresh', '6.8-7.8', 'The Common or Fancy Tail Guppies (Poecilia reticulata) are one of the oldest types and have been popular with hobbyists for over 100 years. They are usually the largest species available in shops and are hardy community fish. They are especially noted for their extensive-tail shapes and distinct, highly bred color morphs.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1008, 'Poecilia', 'reticulata', 'Endlers Guppy', 3.21, FALSE, 'fresh', '6.8-7.8', 'Endlers guppies are closer in appearance to wild-type fish, but still show more variety in their colors and tail shapes than true wild types. They descend from populations collected in the 1960s by the renowned scientist, John Endler.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1009, 'Poecilia', 'picta', 'Swamp Guppy', 3.21, FALSE, 'fresh', '6.8-7.8', 'The Swamp Guppy (Poecilia picta or Micropoecilia picta) is a rare guppy fish that is only been available in the trade for about a decade. Wild populations are often found in coastal streams and estuaries of Trinidad, and they can tolerate brackish aquariums.');

INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1010, 'Neocaridina', 'davidi', 'Red Cherry Shrimp', 4.99, TRUE, 'fresh', '6.8-7.5', 'Red Cherry shrimp are probably the most popular dwarf shrimp among both beginners and more experienced shrimp keepers. And for good reason! This red Neocaridina variety is not too fussy about water values, very easy to breed and quite decorative.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1011, 'Caridina', 'multidentata', 'Amano Shrimp', 2.45, TRUE, 'fresh', '6.8-7.5', 'Amano shrimp are named after the late famous aquascaper Takashi Amano, who first introduce them into the aquarium hobby on a large scale. Though colorless and not too exciting to look at, these shrimp are among the most popular because they are pretty hardy, have a huge appetite for algae and make a great cleaning crew.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1012, 'Neocaridina', 'davidi', 'Blue Dream Shrimp', 7.88, TRUE, 'fresh', '6.8-7.5', 'Blue Dream shrimp are a blue Neocaridina davidi variety: basically a blue version of Red Cherries. Their care requirements are the same, they do not need very specific water values and their striking color makes them a great eyecatcher in any shrimp tank.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1013, 'Palaemonetes', 'paludosus', 'Ghost Shrimp', 0.59, TRUE, 'fresh', '6.8-7.8', 'Ghost shrimp are often sold as cheap food for larger fish species but can also make an interesting permanent addition to the aquarium. They are on this list because they are incredibly hardy and can tolerate bad water values a lot better than most other shrimp. A great option if you are just getting started!');

INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1014, 'Lysmata', 'debelius', 'Blood Red Fire Shrimp', 65.19, TRUE, 'salt', '8.0-8.4', 'Lysmata debelius is a species of cleaner shrimp indigenous to the Indo-Pacific. It is popular in the aquarium trade, where it is known as the fire shrimp, blood shrimp or scarlet cleaner shrimp.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1015, 'Nassarius', 'arcularius', 'Nassarius Snail', 6.58, TRUE, 'salt', '7.9-8.4', 'Unlike many of the more familiar aquarium snails, Nassarius Snails are scavengers and enjoy animal protein. Leftover flakes, fresh frozen food, a dead fish…They will converge on anything that smells good and consume it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1016, 'Amphiprion', 'ocellaris', 'Longfin Ocellaris Clown Fish', 32.74, FALSE, 'salt', '7.8-8.4', 'While not for everyone, the dramatic flowing fins of the ORA Longfin Ocellaris are a striking feature on this otherwise normal orange clownfish. Along with vibrant coloration, their prominent tasseled fins develop rich, black borders that add to the alluring flare this very special fish brings to the home aquarium.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(1017, 'Amphiprion', 'percula', 'Percula Clown Fish', 25.42, FALSE, 'salt', '7.8-8.4', 'Perculas or True Perculas are some of the most classic and popular clownfish species we offer. These docile fish are close relatives of the False Percula (A. ocellaris), and the two species can be easily confused. Both species have orange bodies with three white stripes.');
