-- Fish
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Xiphophorus', 'maculatus', 'Blue Wag Platy', 2.56, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Xiphophorus', 'maculatus', 'Mickey Mouse Platy', 1.67, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Xiphophorus', 'maculatus', 'Painted Platy', 2.14, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Xiphophorus', 'maculatus', 'Sunburst Platy', 2.88, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Xiphophorus', 'maculatus', 'Dalmation Platy', 3.12, FALSE, 'fresh', '7.0-8.0', 'The southern platyfish, common platy or moonfish (Xiphophorus maculatus) is a species of freshwater fish in family Poecilidae of order Cyprinodontiformes. A live-bearer, it is closely related to the green swordtail (X. helleri) and can interbreed with it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Poecilia', 'reticulata', 'Tequila Sunrise Guppy', 3.50, FALSE, 'fresh', '6.8-7.8', 'The Tequila Sunrise Guppy requires an aquarium of at least 10 gallons in size. It is a very peaceful fish and should be housed with tankmates of similar temperament.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Poecilia', 'reticulata', 'Fancy Guppy', 4.65, FALSE, 'fresh', '6.8-7.8', 'The Common or Fancy Tail Guppies (Poecilia reticulata) are one of the oldest types and have been popular with hobbyists for over 100 years. They are usually the largest species available in shops and are hardy community fish. They are especially noted for their extensive-tail shapes and distinct, highly bred color morphs.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Poecilia', 'reticulata', 'Endlers Guppy', 3.21, FALSE, 'fresh', '6.8-7.8', 'Endlers guppies are closer in appearance to wild-type fish, but still show more variety in their colors and tail shapes than true wild types. They descend from populations collected in the 1960s by the renowned scientist, John Endler.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Poecilia', 'picta', 'Swamp Guppy', 3.21, FALSE, 'fresh', '6.8-7.8', 'The Swamp Guppy (Poecilia picta or Micropoecilia picta) is a rare guppy fish that is only been available in the trade for about a decade. Wild populations are often found in coastal streams and estuaries of Trinidad, and they can tolerate brackish aquariums.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Neocaridina', 'davidi', 'Red Cherry Shrimp', 4.99, TRUE, 'fresh', '6.8-7.5', 'Red Cherry shrimp are probably the most popular dwarf shrimp among both beginners and more experienced shrimp keepers. And for good reason! This red Neocaridina variety is not too fussy about water values, very easy to breed and quite decorative.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Caridina', 'multidentata', 'Amano Shrimp', 2.45, TRUE, 'fresh', '6.8-7.5', 'Amano shrimp are named after the late famous aquascaper Takashi Amano, who first introduce them into the aquarium hobby on a large scale. Though colorless and not too exciting to look at, these shrimp are among the most popular because they are pretty hardy, have a huge appetite for algae and make a great cleaning crew.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Neocaridina', 'davidi', 'Blue Dream Shrimp', 7.88, TRUE, 'fresh', '6.8-7.5', 'Blue Dream shrimp are a blue Neocaridina davidi variety: basically a blue version of Red Cherries. Their care requirements are the same, they do not need very specific water values and their striking color makes them a great eyecatcher in any shrimp tank.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Palaemonetes', 'paludosus', 'Ghost Shrimp', 0.59, TRUE, 'fresh', '6.8-7.8', 'Ghost shrimp are often sold as cheap food for larger fish species but can also make an interesting permanent addition to the aquarium. They are on this list because they are incredibly hardy and can tolerate bad water values a lot better than most other shrimp. A great option if you are just getting started!');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Lysmata', 'debelius', 'Blood Red Fire Shrimp', 65.19, TRUE, 'salt', '8.0-8.4', 'Lysmata debelius is a species of cleaner shrimp indigenous to the Indo-Pacific. It is popular in the aquarium trade, where it is known as the fire shrimp, blood shrimp or scarlet cleaner shrimp.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Nassarius', 'arcularius', 'Nassarius Snail', 6.58, TRUE, 'salt', '7.9-8.4', 'Unlike many of the more familiar aquarium snails, Nassarius Snails are scavengers and enjoy animal protein. Leftover flakes, fresh frozen food, a dead fish…They will converge on anything that smells good and consume it.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Amphiprion', 'ocellaris', 'Longfin Ocellaris Clown Fish', 32.74, FALSE, 'salt', '7.8-8.4', 'While not for everyone, the dramatic flowing fins of the ORA Longfin Ocellaris are a striking feature on this otherwise normal orange clownfish. Along with vibrant coloration, their prominent tasseled fins develop rich, black borders that add to the alluring flare this very special fish brings to the home aquarium.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Amphiprion', 'percula', 'Percula Clown Fish', 25.42, FALSE, 'salt', '7.8-8.4', 'Perculas or True Perculas are some of the most classic and popular clownfish species we offer. These docile fish are close relatives of the False Percula (A. ocellaris), and the two species can be easily confused. Both species have orange bodies with three white stripes.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Zebrasoma', 'scopas', 'Scopas Tang', 54.32, FALSE, 'salt', '8.1-8.4', 'The Scopas Tang, also known as the Brown Scopas Tang is yellow, dorsally, and brown, ventrally. These colors gradually get darker from front to back. The body is covered with fine, intricate, light blue markings. The tail is a solid brown color. Juveniles are a little more attractive, with larger dorsal and anal fins and a slightly purplish body color.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Zebrasoma', 'gemmatum', 'Gemmatum Tang', 845.23, FALSE, 'salt', '8.1-8.4', 'The Gemmatum Tang (Zebrasoma gemmatum), also known as the Gem Tang, is a gorgeous and highly-prized fish with stunning black body and a galaxy of vibrant white spots. A vibrant yellow tail and yellow accents on the pectoral fins injects a burst of color for added visual excitement.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Acanthurus', 'leucosternon', 'Powder Blue Tang', 154.36, FALSE, 'salt', '8.1-8.4', 'The Powder Blue Tang, also known as the Powder Blue Surgeonfish, is an iconic marine aquarium fish prized for its vibrant coloration and bold markings. The Powder Blue Tang has a pleasing oval-shaped body showcasing several varying shades of beautiful blue coloration.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Acanthurus', 'triostegus', 'Convict Tang', 36.68, FALSE, 'salt', '8.1-8.4', 'The Convict Tang, also known as the Convict Surgeonfish, boasts an elegantly simple color scheme comprised of a stately ivory-grey body color with hints of creamy yellow coloration that accentuates the dorsal half of the fish. This neutral backdrop provides the perfect stage to showcase six bold vertical black bars, giving the Convict Tang a handsome minimalist appearance.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Pomacentrus', 'smithi', 'Pink Smith Damselfish', 7.26, FALSE, 'salt', '8.0-8.4', 'The Pink Smith Damselfish has a shiny silvertone to white body with pink highlighting the outline. A small group should reside in a 30 gallon or larger aquarium with live rock and other hiding places to break up the territories. Offer the Pink Smith Damselfish a variety of foods including frozen brine and mysis shrimp, dried seaweed, and flake foods.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Dascyllus', 'trimaculatus', 'Three Spot Domino Damselfish', 8.96, FALSE, 'salt', '8.0-8.4', 'The 3-Spot Domino Damselfish, also known as the Three Spot Damselfish, Threespot Dascyllus or Domino Damselfish, is so named due to the three white spots on its black body. It matures into an aggressive adult whose bright spots fade with age and will enter into a relationship with Stichodactyla species (Carpet Anemone) if one is available.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Chrysiptera', 'hemicyanea', 'Azure Damselfish', 20.47, FALSE, 'salt', '8.0-8.4', 'The Damselfish, also known as the Half-blue Damselfish, is a two-tone, darting marine fish. The front portion of the body is bright blue. The posterior portion, anal fin, and tail are yellow. There is a species variation in the amount of yellow on the body of the fish.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Clibanarius', 'sp.', 'Dwarf Red Tip Hermit Crab', 14.14, TRUE, 'salt', '8.1-8.4', 'The Dwarf Red Tip Hermit Crab is a voracious scavenger. Like its Blue Leg cousin, the Dwarf Red Tip Hermit Crab serves as an ideal member of your marine or reef aquariums cleanup crew. Also known simply as the Red Tip Hermit Crab, this omnivore will scavenge all over your live rock and sand substrate - finding its way into the tightest of spaces - to feed on algae and detritus.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Mithraculus', 'sculptus', 'Emerald Crab', 8.99, TRUE, 'salt', '8.1-8.4', 'The Emerald Crab is well respected for its scavenging ability. It will enthusiastically feed on uneaten meaty foods and many types of nuisance algae. Unlike many other animals, Mithraculus sculptus will eat bubble algae and helps clean your aquarium of these algae.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Petrolisthes', 'galathinus', 'Porcelain Crab', 28.99, TRUE, 'salt', '8.1-8.4', 'The Porcelain Crab is common throughout the tropical oceans of the world, and has a flat, round body with two large front claws. These crabs have a pair of front arms called maxillipeds, which have ends that are feather-like in appearance. They use these appendages to filter the water for any passing food.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Nassarius', 'sp.', 'Super Tongan Nassarius Snail', 12.99, TRUE, 'salt', '8.1-8.4', 'The Super Nassarius Snail from Tonga combines unique beauty with unparalleled scavenging abilities. Its oval, spiral shell is often said to resemble an olive pit, but it is much more ornate and elegant in its beauty. The most striking physical characteristic, however, is the long, tube-like siphon that protrudes from one end of the shell.');
INSERT INTO fish(merchID, species, genus, commonName, price, isInvertebrate, waterType, phRange, description) VALUES(NEXTVAL('merchSeq'), 'Engina', 'sp.', 'Bumble Bee Snail', 17.56, TRUE, 'salt', '8.1-8.4', 'The tiny Bumble Bee Snail benefits most marine reef aquariums in big ways. Heralded for their small size and beautiful coloration, Engina sp. can get into small crevices and tight locations between rockwork. Here, they clean away detritus, including uneaten meaty foods and decomposing organisms.');


